# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Harsh Nikarsa

[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "code-model=kernel",
    "-C", "relocation-model=static",
    "-C", "force-frame-pointers=no",
]
