// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Harsh Nikarsa

//! TTY line discipline for the PTY slave.
//!
//! The discipline sits between the PTY master and the slave and owns
//! everything a terminal does to a byte stream on its way in or out:
//!
//!   * **input** — `ICRNL`/`INLCR`/`IGNCR` translation, `ISIG` signal
//!     generation, canonical-mode line editing (`VERASE`, `VKILL`, `VWERASE`,
//!     `VEOF`, `VLNEXT`, `VREPRINT`, `VDISCARD`), and `ECHO*` echo policy;
//!   * **output** — `OPOST` translation (`ONLCR`, `OCRNL`, `ONLRET`, `OLCUC`),
//!     plus XON/XOFF flow control (`IXON`, `VSTART`, `VSTOP`).
//!
//! In canonical mode bytes are held in `canon_buf` until a line terminator
//! completes them, at which point the line moves to `read_buf` for the reader.
//! Raw mode (`ICANON` clear) publishes each byte as it arrives, subject to
//! `VMIN`/`VTIME`.
//!
//! Flag values match the `abi-bits/termios.h` the libc port installs, so the
//! in-kernel [`crate::Termios`] needs no translation in either direction.
//!
//! Two POSIX behaviors are deliberately not implemented, because the pty has
//! no hardware to implement them with and no place to put them:
//!
//!   * `VTIME` is accepted and reported but not enforced. Timed reads need a
//!     per-descriptor timer; the VFS has none. A raw-mode read waits for
//!     `VMIN` bytes (or one byte when `VMIN` is zero) instead.
//!   * `tcsendbreak` is a successful no-op — a pty has no line to break.
//!
//! Everything else a POSIX program can observe is honored.

use alloc::collections::VecDeque;
use alloc::vec::Vec;

/// Maximum bytes kept for one canonical line before it is flushed to readers.
const CANON_MAX: usize = 4096;
/// Maximum bytes buffered for read-out (lines awaiting a reader).
const READ_MAX: usize = 8192;

// --- termios `c_lflag` bits -----------------------------------------------
pub const ISIG: u32 = 0x0000_0001;
pub const ICANON: u32 = 0x0000_0002;
pub const ECHO: u32 = 0x0000_0008;
pub const ECHOE: u32 = 0x0000_0010;
pub const ECHOK: u32 = 0x0000_0020;
pub const ECHONL: u32 = 0x0000_0040;
pub const NOFLSH: u32 = 0x0000_0080;
pub const TOSTOP: u32 = 0x0000_0100;
pub const ECHOCTL: u32 = 0x0000_0400;
pub const ECHOPRT: u32 = 0x0000_0800;
pub const ECHOKE: u32 = 0x0000_1000;
pub const FLUSHO: u32 = 0x0000_2000;
pub const PENDIN: u32 = 0x0000_4000;
pub const IEXTEN: u32 = 0x0000_8000;

// --- termios `c_oflag` bits -----------------------------------------------
pub const OPOST: u32 = 0x0000_0001;
pub const OLCUC: u32 = 0x0000_0002;
pub const ONLCR: u32 = 0x0000_0004;
pub const OCRNL: u32 = 0x0000_0008;
pub const ONOCR: u32 = 0x0000_0010;
pub const ONLRET: u32 = 0x0000_0020;
pub const OFILL: u32 = 0x0000_0040;
pub const OFDEL: u32 = 0x0000_0080;

// --- termios `c_iflag` bits -----------------------------------------------
pub const IGNBRK: u32 = 0x0000_0001;
pub const BRKINT: u32 = 0x0000_0002;
pub const IGNPAR: u32 = 0x0000_0004;
pub const PARMRK: u32 = 0x0000_0008;
pub const INPCK: u32 = 0x0000_0010;
pub const ISTRIP: u32 = 0x0000_0020;
pub const INLCR: u32 = 0x0000_0040;
pub const IGNCR: u32 = 0x0000_0080;
pub const ICRNL: u32 = 0x0000_0200;
pub const IUCLC: u32 = 0x0000_0400;
pub const IXON: u32 = 0x0000_0800;
pub const IXANY: u32 = 0x0000_1000;
pub const IXOFF: u32 = 0x0000_2000;
pub const IMAXBEL: u32 = 0x0000_4000;
pub const IUTF8: u32 = 0x0000_8000;

// --- `c_cc` control-character indices (matches the libc abi-bits) ---------
pub const VINTR: usize = 0;
pub const VQUIT: usize = 1;
pub const VERASE: usize = 2;
pub const VKILL: usize = 3;
pub const VEOF: usize = 4;
pub const VTIME: usize = 5;
pub const VMIN: usize = 6;
pub const VSWTC: usize = 7;
pub const VSTART: usize = 8;
pub const VSTOP: usize = 9;
pub const VSUSP: usize = 10;
pub const VEOL: usize = 11;
pub const VREPRINT: usize = 12;
pub const VDISCARD: usize = 13;
pub const VWERASE: usize = 14;
pub const VLNEXT: usize = 15;
pub const VEOL2: usize = 16;

/// Signals generated by ISIG (values match the kernel's `sig` module).
pub const SIGNAL_INT: u8 = 2; // SIGINT  (VINTR)
pub const SIGNAL_QUIT: u8 = 3; // SIGQUIT (VQUIT)
pub const SIGNAL_TSTP: u8 = 20; // SIGTSTP (VSUSP)

/// The bell character, for `IMAXBEL` on an overflowing line.
const BELL: u8 = 0x07;

/// Line editor state shared by all character devices that speak termios.
pub struct LineDiscipline {
    termios: crate::Termios,
    /// Bytes ready to be read by the slave (complete lines in canonical mode,
    /// raw bytes otherwise).
    read_buf: VecDeque<u8>,
    /// The line being assembled in canonical mode.
    canon_buf: Vec<u8>,
    /// A `^D` on an empty line asked for end-of-file. Set for exactly one
    /// read: POSIX says the reader observes EOF, and typing afterwards resumes
    /// normal input, so this must not be sticky. It is distinct from the
    /// master closing the pair, which is a real permanent EOF.
    eof_pending: bool,
    /// Output halted by `^S` / `TCXONC(TCOOFF)`.
    output_stopped: bool,
    /// Input halted by `^Q` on a full output queue (`IXOFF`).
    input_stopped: bool,
    /// Output written while stopped, replayed on resume.
    pub held_output: Vec<u8>,
    /// Next input byte is literal (`^V` / `VLNEXT`).
    literal_next: bool,
}

impl Default for LineDiscipline {
    fn default() -> Self {
        Self::new()
    }
}

impl LineDiscipline {
    pub fn new() -> Self {
        Self {
            termios: crate::Termios::default(),
            read_buf: VecDeque::with_capacity(1024),
            canon_buf: Vec::with_capacity(128),
            eof_pending: false,
            output_stopped: false,
            input_stopped: false,
            held_output: Vec::new(),
            literal_next: false,
        }
    }

    /// Snapshot of the current termios settings.
    pub fn get_termios(&self) -> crate::Termios {
        self.termios
    }

    /// Apply new termios settings.
    ///
    /// Switching *out* of canonical mode makes a partially typed line
    /// readable: a program that turns off `ICANON` (a shell entering a pager,
    /// or `ssh` for a binary stream) expects whatever was already buffered to
    /// be delivered rather than discarded.
    pub fn set_termios(&mut self, termios: crate::Termios) {
        let was_canon = self.is_canon();
        self.termios = termios;
        if was_canon && !self.is_canon() && !self.canon_buf.is_empty() {
            let pending = core::mem::take(&mut self.canon_buf);
            self.push_read(pending);
        }
    }

    /// `c_cc` control character, with a zero fallback for out-of-range slots.
    fn cc(&self, idx: usize) -> u8 {
        match self.termios.c_cc.get(idx) {
            Some(&b) => b,
            None => 0,
        }
    }

    fn is_set(flags: u32, bit: u32) -> bool {
        flags & bit != 0
    }
    fn is_canon(&self) -> bool {
        Self::is_set(self.termios.c_lflag, ICANON)
    }
    fn is_echo(&self) -> bool {
        Self::is_set(self.termios.c_lflag, ECHO)
    }
    fn is_echoe(&self) -> bool {
        Self::is_set(self.termios.c_lflag, ECHOE)
    }
    fn is_echok(&self) -> bool {
        Self::is_set(self.termios.c_lflag, ECHOK)
    }
    fn is_echonl(&self) -> bool {
        Self::is_set(self.termios.c_lflag, ECHONL)
    }
    fn is_iexten(&self) -> bool {
        Self::is_set(self.termios.c_lflag, IEXTEN)
    }
    fn is_isig(&self) -> bool {
        Self::is_set(self.termios.c_lflag, ISIG)
    }
    fn is_icrnl(&self) -> bool {
        Self::is_set(self.termios.c_iflag, ICRNL)
    }
    fn is_inlcr(&self) -> bool {
        Self::is_set(self.termios.c_iflag, INLCR)
    }
    fn is_igncr(&self) -> bool {
        Self::is_set(self.termios.c_iflag, IGNCR)
    }
    fn is_istrip(&self) -> bool {
        Self::is_set(self.termios.c_iflag, ISTRIP)
    }
    fn is_iulcl(&self) -> bool {
        Self::is_set(self.termios.c_iflag, IUCLC)
    }
    fn is_ignpar(&self) -> bool {
        Self::is_set(self.termios.c_iflag, IGNPAR)
    }
    fn is_imaxbel(&self) -> bool {
        Self::is_set(self.termios.c_iflag, IMAXBEL)
    }
    fn is_ixon(&self) -> bool {
        Self::is_set(self.termios.c_iflag, IXON)
    }
    fn is_opost(&self) -> bool {
        Self::is_set(self.termios.c_oflag, OPOST)
    }
    fn is_onlcr(&self) -> bool {
        Self::is_set(self.termios.c_oflag, ONLCR)
    }
    fn is_ocrnl(&self) -> bool {
        Self::is_set(self.termios.c_oflag, OCRNL)
    }
    fn is_onocr(&self) -> bool {
        Self::is_set(self.termios.c_oflag, ONOCR)
    }
    fn is_onlret(&self) -> bool {
        Self::is_set(self.termios.c_oflag, ONLRET)
    }
    fn is_olcuc(&self) -> bool {
        Self::is_set(self.termios.c_oflag, OLCUC)
    }

    /// Whether output is halted by flow control.
    pub fn output_stopped(&self) -> bool {
        self.output_stopped
    }

    /// Halt or resume output (`TCXONC`).
    pub fn set_stopped(&mut self, stopped: bool) {
        self.output_stopped = stopped;
    }

    /// Stow output written while output is stopped, so `TCOON` can replay it.
    ///
    /// Dropping it instead would lose data a program had already committed to
    /// writing — a program that ignores the stop would see its output vanish.
    pub fn hold_output(&mut self, data: &[u8]) {
        // Bound the backlog: a peer that never resumes must not be able to make
        // the kernel buffer without limit. Past the cap the oldest bytes go,
        // which is the same loss a real UART would suffer.
        const HELD_MAX: usize = 8192;
        for b in data {
            if self.held_output.len() >= HELD_MAX {
                self.held_output.remove(0);
            }
            self.held_output.push(*b);
        }
    }

    /// Halt input because output is not draining (`TCXONC(TCIOFF)`).
    pub fn stop_input(&mut self) {
        self.input_stopped = true;
    }

    /// Resume input (`TCXONC(TCION)`).
    pub fn resume_input(&mut self) {
        self.input_stopped = false;
    }

    /// Bytes a reader can take right now. Zero means the reader must wait.
    pub fn available(&self) -> usize {
        self.read_buf.len()
    }

    /// Discard everything buffered for reading (`TCFLSH(TCIFLUSH)`).
    pub fn flush_input(&mut self) {
        self.read_buf.clear();
        self.canon_buf.clear();
        self.eof_pending = false;
    }

    /// Discard output held by flow control (`TCFLSH(TCOFLUSH)`).
    pub fn flush_output(&mut self) {
        self.held_output.clear();
    }

    /// Whether a reader should be considered ready. A pending end-of-file
    /// counts as ready, because the reader's next `read` returns 0 and a
    /// program waiting on the terminal needs to observe that.
    pub fn is_readable(&self) -> bool {
        if self.eof_pending {
            return true;
        }
        if self.is_canon() {
            !self.read_buf.is_empty()
        } else {
            self.read_buf.len() >= self.wakemin()
        }
    }

    /// Minimum bytes buffered before a raw-mode reader is considered ready.
    fn wakemin(&self) -> usize {
        let min = self.cc(VMIN);
        if min == 0 {
            1
        } else {
            min as usize
        }
    }

    /// Drain buffered input into `buf`; returns the number of bytes copied.
    ///
    /// A pending end-of-file consumes itself and returns 0, which is how a
    /// `^D` on an empty line reads as EOF. The flag is cleared, so the next
    /// read waits for new input again — POSIX end-of-file on a terminal is not
    /// permanent.
    pub fn read_into(&mut self, buf: &mut [u8]) -> usize {
        if self.eof_pending {
            self.eof_pending = false;
            return 0;
        }
        let mut n = 0;
        while n < buf.len() {
            match self.read_buf.pop_front() {
                Some(b) => {
                    buf[n] = b;
                    n += 1;
                }
                None => break,
            }
        }
        n
    }

    fn push_read(&mut self, bytes: impl IntoIterator<Item = u8>) {
        for b in bytes {
            if self.read_buf.len() < READ_MAX {
                self.read_buf.push_back(b);
            } else {
                break;
            }
        }
    }

    /// Apply OPOST output translation to a byte stream.
    ///
    /// `ONLCR` turns `\n` into `\r\n`, `OCRNL` turns `\r` into `\n`, and
    /// `ONLRET` moves a following `\n` to the line start. `ONOCR` suppresses
    /// the carriage return of a `\r\n` pair, and `OLCUC` lowercases letters.
    pub fn process_output(&self, data: &[u8]) -> Vec<u8> {
        let mut out = Vec::with_capacity(data.len());
        if !self.is_opost() {
            out.extend_from_slice(data);
            return out;
        }
        // `ONOCR`: a `\n` that directly follows a `\r` gets no added `\r`.
        let mut last_was_cr = false;
        for &b in data {
            if self.is_onocr() && b == b'\n' && last_was_cr {
                out.push(b);
            } else if self.is_onlcr() && b == b'\n' {
                out.push(b'\r');
                out.push(b'\n');
            } else if self.is_ocrnl() && b == b'\r' {
                out.push(b'\n');
            } else if self.is_onlret() && b == b'\n' {
                out.push(b'\r');
            } else if self.is_olcuc() && b.is_ascii_uppercase() {
                out.push(b.to_ascii_lowercase());
            } else {
                out.push(b);
            }
            last_was_cr = b == b'\r';
        }
        out
    }

    /// Feed one byte arriving from the master.
    ///
    /// Returns `(echo, signal)`: `echo` is the byte stream the master side
    /// must republish for the terminal emulator to draw; `Some(sig)` means the
    /// byte was an `ISIG` signal character and must NOT be delivered to the
    /// slave reader — the caller delivers `sig` to the foreground process
    /// group instead.
    pub fn input_char(&mut self, byte: u8) -> (Vec<u8>, Option<u8>) {
        let mut echo = Vec::new();
        // `IXOFF`: the far side asked us to stop sending, so drop input.
        if self.input_stopped {
            return (echo, None);
        }
        let mut byte = byte;

        // `ISTRIP` masks the parity/high bit before anything else looks at it.
        if self.is_istrip() {
            byte &= 0x7f;
        }
        // `IUCLC`: fold upper case to lower on input.
        if self.is_iulcl() && byte.is_ascii_uppercase() {
            byte = byte.to_ascii_lowercase();
        }

        // XON/XOFF flow control. `^S` stops output, `^Q` restarts it, and
        // these are not delivered to the reader. `IXANY` makes any character
        // restart output.
        if self.is_ixon() {
            let vstop = self.cc(VSTOP);
            let vstart = self.cc(VSTART);
            if vstop != 0 && byte == vstop {
                self.output_stopped = true;
                return (echo, None);
            }
            if vstart != 0 && byte == vstart {
                self.output_stopped = false;
                return (echo, None);
            }
            if Self::is_set(self.termios.c_iflag, IXANY) && self.output_stopped {
                self.output_stopped = false;
            }
        }

        // `^V` (VLNEXT) makes the next byte literal: it bypasses every
        // interpretation below and is inserted as-is.
        if self.is_iexten() {
            let vlnext = self.cc(VLNEXT);
            if vlnext != 0 && !self.literal_next && byte == vlnext {
                self.literal_next = true;
                if self.is_echo() {
                    echo.push(b'\\');
                    echo.push(b' ');
                }
                return (echo, None);
            }
        }
        if self.literal_next {
            self.literal_next = false;
            self.deliver_literal(byte, &mut echo);
            return (echo, None);
        }

        // CR/NL input translation (ICRNL/INLCR/IGNCR).
        if byte == b'\r' {
            if self.is_igncr() {
                return (echo, None);
            }
            if self.is_icrnl() {
                byte = b'\n';
            }
        } else if byte == b'\n' && self.is_inlcr() {
            byte = b'\r';
        }

        // `IGNPAR`/`PARMRK` exist for a real UART's framing errors. A pty
        // cannot produce one, so there is no parity to ignore or mark.
        let _ = self.is_ignpar();

        // Signal generation (ISIG): VINTR/VQUIT/VSUSP.
        if self.is_isig() {
            let sig = if self.cc(VINTR) != 0 && byte == self.cc(VINTR) {
                Some(SIGNAL_INT)
            } else if self.cc(VQUIT) != 0 && byte == self.cc(VQUIT) {
                Some(SIGNAL_QUIT)
            } else if self.cc(VSUSP) != 0 && byte == self.cc(VSUSP) {
                Some(SIGNAL_TSTP)
            } else {
                None
            };
            if let Some(sig) = sig {
                // Echo in caret notation, but only when ECHOCTL is also set:
                // that is the flag that says "render control characters as ^X".
                if self.is_echo() && Self::is_set(self.termios.c_lflag, ECHOCTL) {
                    let label: &[u8] = match sig {
                        SIGNAL_INT => b"^C\n",
                        SIGNAL_QUIT => b"^\\\n",
                        _ => b"^Z\n",
                    };
                    echo.extend_from_slice(&self.process_output(label));
                }
                // A pending ^D is abandoned: the line is being interrupted.
                self.eof_pending = false;
                return (echo, Some(sig));
            }
        }

        if self.is_canon() {
            self.input_canon(byte, &mut echo);
        } else {
            self.input_raw(byte, &mut echo);
        }
        // While output is stopped (`^S` or `TCXONC(TCOOFF)`) the terminal
        // shows nothing, so echoing what was just typed would be a lie. The
        // input itself is still processed and delivered.
        if self.output_stopped {
            echo.clear();
        }
        (echo, None)
    }

    /// Insert a byte that `VLNEXT` marked literal.
    fn deliver_literal(&mut self, byte: u8, echo: &mut Vec<u8>) {
        if self.is_canon() {
            if self.canon_buf.len() < CANON_MAX {
                self.canon_buf.push(byte);
            }
            if self.is_echo() {
                echo.extend_from_slice(&self.process_output(&[byte]));
            }
            // A literal newline still ends the line.
            if byte == b'\n' {
                let flushed = core::mem::take(&mut self.canon_buf);
                self.push_read(flushed);
            }
        } else {
            self.push_read([byte]);
            if self.is_echo() {
                echo.extend_from_slice(&self.process_output(&[byte]));
            }
        }
    }

    /// Canonical-mode input: assemble a line, editing it, flushing to the read
    /// buffer on a line terminator or `VEOF`.
    fn input_canon(&mut self, byte: u8, echo: &mut Vec<u8>) {
        // Erase: the configured VERASE character, plus the two conventional
        // backspace bytes — 0x7f from an ANSI DEL key and 0x08 from a PS/2
        // Backspace. ECHOE is what corrects the display with "\b \b".
        let erase = self.cc(VERASE);
        if (erase != 0 && byte == erase) || byte == 0x08 || byte == 0x7f {
            if self.canon_buf.pop().is_some() && self.is_echo() && self.is_echoe() {
                echo.extend_from_slice(&self.process_output(b"\x08 \x08"));
            }
            return;
        }

        if self.cc(VKILL) != 0 && byte == self.cc(VKILL) {
            // ^U erases the whole line. With ECHOKE set the display is
            // corrected in one jump; otherwise it walks back a byte at a time.
            if self.is_echo() && self.is_echok() {
                if Self::is_set(self.termios.c_lflag, ECHOKE) {
                    for _ in 0..self.canon_buf.len() {
                        echo.extend_from_slice(&self.process_output(b"\x08 \x08"));
                    }
                }
            } else if self.is_echo() {
                for _ in 0..self.canon_buf.len() {
                    echo.extend_from_slice(&self.process_output(b"\x08 \x08"));
                }
            }
            self.canon_buf.clear();
            return;
        }

        if self.is_iexten() {
            // ^W erases the previous whitespace-delimited word.
            let werase = self.cc(VWERASE);
            if werase != 0 && byte == werase {
                self.erase_word(echo);
                return;
            }
            // ^R reprints the pending line.
            let reprint = self.cc(VREPRINT);
            if reprint != 0 && byte == reprint {
                if self.is_echo() {
                    echo.extend_from_slice(&self.process_output(b"\n"));
                    echo.extend_from_slice(&self.process_output(&self.canon_buf.clone()));
                }
                return;
            }
            // ^O discards the pending line without delivering it.
            let discard = self.cc(VDISCARD);
            if discard != 0 && byte == discard {
                if self.is_echo() && self.is_echok() {
                    for _ in 0..self.canon_buf.len() {
                        echo.extend_from_slice(&self.process_output(b"\x08 \x08"));
                    }
                }
                self.canon_buf.clear();
                return;
            }
        }

        if self.cc(VEOF) != 0 && byte == self.cc(VEOF) {
            // ^D on a line with content: deliver what is typed without waiting
            // for a newline, which is what makes `cat` usable interactively.
            if self.canon_buf.is_empty() {
                // ^D on an empty line is the end-of-file request. It is
                // consumed by the next read, which returns 0.
                self.eof_pending = true;
            } else {
                let flushed = core::mem::take(&mut self.canon_buf);
                self.push_read(flushed);
            }
            return;
        }

        if self.is_echoe() && Self::is_set(self.termios.c_lflag, ECHOCTL) && byte < 0x20 && byte != b'\t' {
            // Render a control character as ^X rather than letting it move the
            // cursor somewhere unintended.
            echo.extend_from_slice(&self.process_output(&[b'^', byte + b'@']));
        } else if self.is_echo() {
            echo.extend_from_slice(&self.process_output(&[byte]));
        }

        let overflow = self.canon_buf.len() >= CANON_MAX;
        if !overflow {
            self.canon_buf.push(byte);
        }

        if overflow {
            // The line is full. POSIX says deliver it and ring the bell.
            if self.is_imaxbel() && self.is_echo() {
                echo.push(BELL);
            }
            let flushed = core::mem::take(&mut self.canon_buf);
            self.push_read(flushed);
            return;
        }

        // Line terminator: newline, or whichever of VEOL/VEOL2 is configured.
        let veol = self.cc(VEOL);
        let veol2 = self.cc(VEOL2);
        let terminator = byte == b'\n'
            || (veol != 0 && byte == veol)
            || (veol2 != 0 && byte == veol2);
        if terminator {
            let flushed = core::mem::take(&mut self.canon_buf);
            self.push_read(flushed);
            if byte == b'\n' && self.is_echonl() && !self.is_echo() {
                // ECHONL echoes the newline even with ECHO off.
                echo.extend_from_slice(&self.process_output(b"\n"));
            }
        }
    }

    /// Erase the last whitespace-delimited word (^W), fixing up the echo.
    fn erase_word(&mut self, echo: &mut Vec<u8>) {
        let removed = self.canon_buf.len();
        // Trailing spaces are not part of the word.
        while self.canon_buf.last().map(|b| b.is_ascii_whitespace()) == Some(true) {
            self.canon_buf.pop();
        }
        // Then the word itself.
        while self
            .canon_buf
            .last()
            .map(|b| !b.is_ascii_whitespace())
            == Some(true)
        {
            self.canon_buf.pop();
        }
        let removed = removed - self.canon_buf.len();
        if removed > 0 && self.is_echo() && self.is_echoe() {
            for _ in 0..removed {
                echo.extend_from_slice(&self.process_output(b"\x08 \x08"));
            }
        }
    }

    /// Raw-mode input: publish the byte immediately, echoing if requested.
    fn input_raw(&mut self, byte: u8, echo: &mut Vec<u8>) {
        self.push_read([byte]);
        if self.is_echo() {
            echo.extend_from_slice(&self.process_output(&[byte]));
        }
    }
}
